import re
import ast
import json
from openai import OpenAI

# ------------------------------------------------------------------------------
# 1. API SERVER CONFIGURATION
# ------------------------------------------------------------------------------
# Configured for local inference execution environments (e.g., vLLM cluster).
# If migrating to an external commercial API provider, substitute "EMPTY" with your 
# actual environment token string and target the appropriate cloud provider base_url endpoint.
client = OpenAI(
    api_key="EMPTY", 
    base_url="http://localhost:8000/v1/"
)


# ------------------------------------------------------------------------------
# 2. DICTIONARY EXTRACTION
# ------------------------------------------------------------------------------
def extract_dict(text):
    """
    Isolates and extracts the first JSON/Dictionary block found within raw LLM string text.

    Args:
        text (str): The raw unstructured string output generated by the LLM.

    Returns:
        dict or None: Validated Python dictionary if parsing succeeds, otherwise None.
    """
    # Pattern to isolate string matches encapsulated within curly brackets
    pattern = r"(\{.*?\})"
    match = re.search(pattern, text, re.DOTALL)
    
    if match:
        dict_text = match.group(1).strip()
        try:
            # Handle standard JavaScript null assignments defensively for python evaluation safety
            dict_text = dict_text.replace("null", "None")  
            return ast.literal_eval(dict_text)
        except Exception as e:
            print("Error parsing dict:", e)
            return None
    else:
        print("No dictionary found.")
        return None


# ------------------------------------------------------------------------------
# 3. PROMPT GENERATION
# ------------------------------------------------------------------------------
def create_prompt(sentence, prompt_template_path):
    """
    Builds a robust, multi-tier prompt framework using a structured JSON configuration file.

    Args:
        sentence (str): The raw sentence to be processed.
        prompt_template_path (str): Filepath pointing to the JSON prompt matrix template.

    Returns:
        str: Fully concatenated text prompt containing contextual constraints.
    """
    with open(prompt_template_path, 'r') as file:
        template_data = json.load(file)
    
    # Parse core layout parameters out of JSON payload safely
    description = template_data.get("description", "")
    instructions = "\n".join(template_data.get("instructions", []))
    notes = "\n".join(template_data.get("notes", []))
    formatting_rules = "\n".join(template_data.get("formatting_rules", []))
    sentence_part = template_data.get("template", "").format(text=sentence)

    # Construct unified runtime layout string block
    full_prompt = f"""{description}

    {instructions}

    {notes}

    {formatting_rules}

    {sentence_part}
    """
    return full_prompt


# ------------------------------------------------------------------------------
# 4. LLM INFERENCE CALL
# ------------------------------------------------------------------------------
def extract_features_from_text(sentence, prompt_template_path, token, model_name="RedHatAI/Llama-3.1-8B-Instruct", temp_val=0, top_p=1.0):
    """
    Dispatches a structured text prompt to the backend LLM engine and returns the parsed metrics.

    Args:
        sentence (str): Text sample under analysis.
        prompt_template_path (str): Target filesystem location of the text rules matrix.
        token (int): Maximum limits placed on tokens during text generation runtime.
        model_name (str): Exact namespace identifier string of the endpoint's model.
        temp_val (float): Control scaling variable handling randomness characteristics.
        top_p (float): Threshold determining cumulative nucleus probability scope sets.

    Returns:
        dict: Populated data attributes mapping results; falls back to an empty dictionary on failure.
    """
    # Compile text constraints
    prompt = create_prompt(sentence, prompt_template_path)

    # Request generation completions directly through the client interface
    chat_response = client.completions.create(
        model=model_name,
        prompt=prompt,
        max_tokens=token,
        temperature=temp_val,
        top_p=top_p
    )

    # Format response strings safely
    output_text = chat_response.choices[0].text.strip()
    
    # UNCOMMENT TO AUDIT RAW, UNPARSED OUTBOUND STRINGS DIRECTLY FROM THE ENDPOINT:
    # print('-----Hide this print after use----')
    # print(output_text)
    
    # Clean textual parameters and reduce boundaries into an internal dict structure
    llm_dict = extract_dict(output_text)  
    
    # Enforce safe data constraints on empty returns
    if llm_dict is None:
        llm_dict = {}
        
        # UNCOMMENT TO REVIEW SPECIFIC SENTENCES TRIGGERING LOGICAL PARSING CONFLICTS:
        # print('-----Remove the print command after use------')
        # print(sentence)

    return llm_dict



def compare_list(ls1, ls2, operation_type='common'):
    """
    Performs set operations between two lists and returns the result as a list.

    Args:
        ls1 (list): The first list.
        ls2 (list): The second list.
        operation_type (str): The type of set operation to perform.
                              Options: 'common', 'disjoint', 'diff_ls1', 'diff_ls2'.
                              Defaults to 'common'.

    Returns:
        list: The result of the specified set operation.
              Returns an empty list if an invalid operation_type is provided.
    """
    set1 = set(ls1)
    set2 = set(ls2)

    if operation_type == 'common':
        return list(set1.intersection(set2))
    elif operation_type == 'disjoint':
        return list(set1.symmetric_difference(set2))
    elif operation_type == 'diff_ls1':
        return list(set1.difference(set2))
    elif operation_type == 'diff_ls2':
        return list(set2.difference(set1))
    else:
        print(f"Warning: Invalid operation_type '{operation_type}'. Returning empty list.")
        return []
    

    
    
    
def harmonize_plot_data(
    plot_data, 
    rename_dict
):
    """
    Harmonize + reorder plot_data using rename_dict order.

    What it does
    ----------------
    1. Keeps ONLY pathology features present in rename_dict
    2. Uses rename_dict ORDER as final order
    3. Renames all pathology rows/index/labels
    4. Keeps sample_counts synced
    5. Keeps prs_labels untouched
    """

    # --------------------------------------------------
    # deep copy
    # --------------------------------------------------
    new_plot_data = copy.deepcopy(plot_data)

    original_labels = plot_data["path_labels"]

    # --------------------------------------------------
    # IMPORTANT:
    # order is taken FROM rename_dict
    # --------------------------------------------------
    keep_labels = [
        k for k in rename_dict.keys()
        if k in original_labels
    ]

    # renamed labels in SAME order
    renamed_labels = [
        rename_dict[k]
        for k in keep_labels
    ]

    # --------------------------------------------------
    # dataframe keys
    # --------------------------------------------------
    df_keys = [
        "corr_matrix",
        "dot_size",
        "sig_mask",
        "star_size"
    ]

    # --------------------------------------------------
    # reorder + rename dataframes
    # --------------------------------------------------
    for key in df_keys:

        df = new_plot_data[key].copy()

        # reorder rows using keep_labels order
        df = df.loc[keep_labels]

        # rename rows
        df.index = renamed_labels

        new_plot_data[key] = df

    # --------------------------------------------------
    # sample_counts synced to same order
    # --------------------------------------------------
    label_to_count = dict(
        zip(original_labels, plot_data["sample_counts"])
    )

    new_plot_data["sample_counts"] = [
        label_to_count[k]
        for k in keep_labels
    ]

    # --------------------------------------------------
    # update labels
    # --------------------------------------------------
    new_plot_data["path_labels"] = renamed_labels

    # prs labels unchanged
    new_plot_data["prs_labels"] = plot_data["prs_labels"]

    # keep p-values unchanged
    new_plot_data["p_min"] = plot_data["p_min"]
    new_plot_data["p_max"] = plot_data["p_max"]

    return new_plot_data



def harmonize_plot_data_columns(
    plot_data, 
    rename_dict
):
    """
    Harmonize + reorder PRS columns using rename_dict order.

    What it does
    ----------------
    1. Keeps ONLY PRS columns present in rename_dict
    2. Uses rename_dict ORDER as final order
    3. Renames:
        - corr_matrix columns
        - dot_size columns
        - sig_mask columns
        - star_size columns
        - prs_labels
    4. Keeps pathology rows and sample_counts unchanged
    """

    new_plot_data = copy.deepcopy(plot_data)

    original_prs = plot_data["prs_labels"]

    # --------------------------------------------------
    # IMPORTANT:
    # order comes FROM rename_dict
    # --------------------------------------------------
    keep_prs = [
        k for k in rename_dict.keys()
        if k in original_prs
    ]

    renamed_prs = [
        rename_dict[k]
        for k in keep_prs
    ]

    # --------------------------------------------------
    # dataframe keys
    # --------------------------------------------------
    df_keys = [
        "corr_matrix",
        "dot_size",
        "sig_mask",
        "star_size"
    ]

    # --------------------------------------------------
    # reorder + rename columns
    # --------------------------------------------------
    for key in df_keys:

        df = new_plot_data[key].copy()

        # reorder columns using dict order
        df = df[keep_prs]

        # rename columns
        df.columns = renamed_prs

        new_plot_data[key] = df

    # --------------------------------------------------
    # update labels
    # --------------------------------------------------
    new_plot_data["prs_labels"] = renamed_prs

    # unchanged
    new_plot_data["path_labels"] = plot_data["path_labels"]
    new_plot_data["sample_counts"] = plot_data["sample_counts"]

    # unchanged
    new_plot_data["p_min"] = plot_data["p_min"]
    new_plot_data["p_max"] = plot_data["p_max"]

    return new_plot_data




from seaborn.matrix import _HeatMapper
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd


from seaborn.utils import despine, axis_ticklabels_overlap, relative_luminance, to_utf8
from six import string_types

class _ScatterMapper(_HeatMapper):
    """
    Draw a scattermap plot, similar to heatmap plot, but use scatter dots instead of heatmap
    """

    def __init__(self, data,
                 marker, marker_size,
                 vmin, vmax, cmap, center, robust, cbar, cbar_kws,
                 xticklabels=True, yticklabels=True, mask=None):

        super(_ScatterMapper, self).__init__(
            data, vmin, vmax, cmap, center, robust, cbar=cbar, cbar_kws=cbar_kws,
            xticklabels=xticklabels, yticklabels=yticklabels, mask=mask,
            # Don't support annotation
            annot=False, fmt=None, annot_kws=None,
        )

        self.marker = marker

        if isinstance(marker_size, float) or isinstance(marker_size, int):
            self.marker_size = marker_size
        elif isinstance(marker_size, pd.DataFrame):
            self.marker_size = marker_size.loc[self.data.index, self.data.columns].values
        else:
            self.marker_size = marker_size
        
    def plot(self, ax, cax, kws):
        """Draw the scattermap on the provided Axes."""
        # Remove all the Axes spines
        despine(ax=ax, left=True, bottom=True)

        # Draw the heatmap
        data = self.plot_data

        range_y = np.arange(data.shape[0], dtype=int) + 0.5
        range_x = np.arange(data.shape[1], dtype=int) + 0.5
        x, y = np.meshgrid(range_x, range_y)

        hmap = ax.scatter(x, y,
                          c=data,
                          marker=self.marker,
                          cmap=self.cmap,
                          vmin=self.vmin, vmax=self.vmax,
                          s=self.marker_size, **kws)

        # Set the axis limits
        ax.set(xlim=(0, self.data.shape[1]), ylim=(0, self.data.shape[0]))

        # Possibly add a colorbar
        if self.cbar:
            cb = ax.figure.colorbar(hmap, cax, ax, **self.cbar_kws)
            cb.outline.set_linewidth(0)
            # If rasterized is passed to pcolormesh, also rasterize the
            # colorbar to avoid white lines on the PDF rendering
            if kws.get('rasterized', False):
                cb.solids.set_rasterized(True)

        # Add row and column labels
        if isinstance(self.xticks, string_types) and self.xticks == "auto":
            xticks, xticklabels = self._auto_ticks(ax, self.xticklabels, 0)
        else:
            xticks, xticklabels = self.xticks, self.xticklabels

        if isinstance(self.yticks, string_types) and self.yticks == "auto":
            yticks, yticklabels = self._auto_ticks(ax, self.yticklabels, 1)
        else:
            yticks, yticklabels = self.yticks, self.yticklabels

        ax.set(xticks=xticks, yticks=yticks)
        xtl = ax.set_xticklabels(xticklabels)
        #ytl = ax.set_yticklabels(yticklabels, rotation="vertical")
        ytl = ax.set_yticklabels(yticklabels, rotation=0)

        # Possibly rotate them if they overlap
        ax.figure.draw(ax.figure.canvas.get_renderer())
        if axis_ticklabels_overlap(xtl):
            plt.setp(xtl, rotation="vertical")
        if axis_ticklabels_overlap(ytl):
            plt.setp(ytl, rotation="horizontal")

        # Add the axis labels
        ax.set(xlabel=self.xlabel, ylabel=self.ylabel)

        # Annotate the cells with the formatted values
        if self.annot:
            self._annotate_heatmap(ax, hmap)

        # Invert the y axis to show the plot in matrix form
        ax.invert_yaxis()

def scattermap(data,
               marker='o',
               marker_size=100,
               vmin=None, vmax=None, cmap=None, center=None, robust=False,
               linewidths=0, linecolor="black",
               cbar=True, cbar_kws=None, cbar_ax=None,
               square=False, xticklabels="auto", yticklabels="auto",
               mask=None, ax=None, **kwargs):
    """Plot rectangular data as a color-encoded matrix.

    This function is similar to `sns.heatmap`, as it is an Axes-level function that will draw the
    heatmap into the currently-active Axes if none is provided to the ``ax`` argument.

    The main difference is that instead of drawing an actual heatmap with filled squares,
    this function will use the `plt.scatter` behind the scenes to draw a scatterplot-heatmap.

    The default is set to plot a grid of circles, however this can be changed via `marker`
    parameter.

    Parameters
    ----------
    data : rectangular dataset
        2D dataset that can be coerced into an ndarray. If a Pandas DataFrame
        is provided, the index/column information will be used to label the
        columns and rows.
    marker: string, optional
        Marker to use: any marker that `pyplot.scatter` supports. Defaults to circle.
    marker_size: int or rectangular dataset
        Either an integer to set the marker size of all data points to,
        or a 2D dataset (like in `data`) that sets individual point sizes.
        Defaults to 100.
    vmin, vmax : floats, optional
        Values to anchor the colormap, otherwise they are inferred from the
        data and other keyword arguments.
    cmap : matplotlib colormap name or object, or list of colors, optional
        The mapping from data values to color space. If not provided, the
        default will depend on whether ``center`` is set.
    center : float, optional
        The value at which to center the colormap when plotting divergant data.
        Using this parameter will change the default ``cmap`` if none is
        specified.
    robust : bool, optional
        If True and ``vmin`` or ``vmax`` are absent, the colormap range is
        computed with robust quantiles instead of the extreme values.
    linewidths : float, optional
        Width of the border lines that will surround the markers
    linecolor : color, optional
        Color of the border lines to the markers
    cbar : boolean, optional
        Whether to draw a colorbar.
    cbar_kws : dict of key, value mappings, optional
        Keyword arguments for `fig.colorbar`.
    cbar_ax : matplotlib Axes, optional
        Axes in which to draw the colorbar, otherwise take space from the
        main Axes.
    square : boolean, optional
        If True, set the Axes aspect to "equal" so each cell will be
        square-shaped.
    xticklabels, yticklabels : "auto", bool, list-like, or int, optional
        If True, plot the column names of the dataframe. If False, don't plot
        the column names. If list-like, plot these alternate labels as the
        xticklabels. If an integer, use the column names but plot only every
        n label. If "auto", try to densely plot non-overlapping labels.
    mask : boolean array or DataFrame, optional
        If passed, data will not be shown in cells where ``mask`` is True.
        Cells with missing values are automatically masked.
    ax : matplotlib Axes, optional
        Axes in which to draw the plot, otherwise use the currently-active
        Axes.
    kwargs : other keyword arguments
        All other keyword arguments are passed to ``ax.pcolormesh``.

    Returns
    -------
    ax : matplotlib Axes
        Axes object with the heatmap.

    See also
    --------
    clustermap : Plot a matrix using hierachical clustering to arrange the
                 rows and columns.

    Examples
    --------

    Plot a scattermap for a numpy array:

    .. plot::
        :context: close-figs

        >>> import numpy as np; np.random.seed(0)
        >>> import seaborn as sns; sns.set()
        >>> uniform_data = np.random.rand(10, 12)
        >>> ax = scattermap(uniform_data)

    Draw on white axes

    .. plot::
        :context: close-figs

        >>> uniform_data = np.random.rand(10, 12)
        >>> with sns.axes_style("white"):
        ...     ax = scattermap(uniform_data)

    Change the limits of the scattermap:

    .. plot::
        :context: close-figs

        >>> ax = scattermap(uniform_data, vmin=0, vmax=1)

    Plot a scattermap for data centered on 0 with a diverging colormap:

    .. plot::
        :context: close-figs

        >>> normal_data = np.random.randn(10, 12)
        >>> ax = scattermap(normal_data, center=0)

    Plot a dataframe with meaningful row and column labels:

    .. plot::
        :context: close-figs

        >>> flights = sns.load_dataset("flights")
        >>> flights = flights.pivot("month", "year", "passengers")
        >>> ax = scattermap(flights)

    Add border lines around each glyph:

    .. plot::
        :context: close-figs

        >>> ax = scattermap(flights, linewidths=1, linecolor='black')

    Use a different colormap:

    .. plot::
        :context: close-figs

        >>> ax = scattermap(flights, cmap="YlGnBu")

    Center the colormap at a specific value:

    .. plot::
        :context: close-figs

        >>> ax = scattermap(flights, center=flights.loc["January", 1955])

    Plot every other column label and don't plot row labels:

    .. plot::
        :context: close-figs

        >>> data = np.random.randn(50, 20)
        >>> ax = scattermap(data, xticklabels=2, yticklabels=False)

    Don't draw a colorbar:

    .. plot::
        :context: close-figs

        >>> ax = scattermap(flights, cbar=False)

    Use different axes for the colorbar:

    .. plot::
        :context: close-figs

        >>> grid_kws = {"height_ratios": (.9, .05), "hspace": .3}
        >>> f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
        >>> ax = scattermap(flights, ax=ax,
        ...                  cbar_ax=cbar_ax,
        ...                  cbar_kws={"orientation": "horizontal"})

    Use a mask to plot only part of a matrix

    .. plot::
        :context: close-figs

        >>> corr = np.corrcoef(np.random.randn(10, 200))
        >>> mask = np.zeros_like(corr)
        >>> mask[np.triu_indices_from(mask)] = True
        >>> with sns.axes_style("white"):
        ...     ax = scattermap(corr, mask=mask, vmax=.3, square=True)

     Change glyph, plot stars instead of circles

    .. plot::
        :context: close-figs

        >>> ax = scattermap(corr, vmax=.3, square=True, marker='*')


    Plot multiple markers on the same plot

    >>> corr = np.corrcoef(np.random.randn(10, 200))
    >>> mask = np.zeros_like(corr)
    >>> mask[np.triu_indices_from(mask)] = True
    >>> with sns.axes_style("white"):
    ...     ax = scattermap(corr, mask=mask, vmax=.3, square=True)
    ...     ax = scattermap(corr, mask=mask.T, vmax=.3, square=True, ax=ax, marker='*', cbar=False)

    Specify size for points

    .. plot::
        :context: close-figs

    >>> with sns.axes_style("white"):
    ...     ax = scattermap(corr, vmax=.3, square=True, marker_size=np.abs(corr)*300)

    """
    # Initialize the plotter object
    plotter = _ScatterMapper(data,
                             marker, marker_size,
                             vmin, vmax, cmap, center, robust,
                             cbar, cbar_kws, xticklabels,
                             yticklabels, mask)

    # Add the pcolormesh kwargs here
    kwargs["linewidths"] = linewidths
    kwargs["edgecolor"] = linecolor

    # Draw the plot and return the Axes
    if ax is None:
        ax = plt.gca()
    if square:
        ax.set_aspect("equal")
    plotter.plot(ax, cbar_ax, kwargs)
    return ax
# ==============================================================================
# PREDEFINED PATHOLOGY MAPPINGS & CONFIGURABLE FEATURE SELECTION
# ==============================================================================
# CAUTION: Ensure dictionary keys strictly match your input table column headers. 
# Name mismatches or typos will result in lookup errors during execution.

# --- [INDICATIVE MAPPINGS: Replace keys/values with your exact table conventions] ---
shade_mapping = {
    # --- Alzheimer's Cluster ---
    "APOE": "APOE",
    "AD (without APOE)": "AD (APOE-)",
    "Amyloid-β Plaques (APOE Removed)": "Amyloid-β spread (Thal phase; APOE−)",
    "Braak NFT Stage (APOE Removed)": "Tau Neurofibrillary tangle spread (Braak Stage; APOE−)",
    "CERAD Score (APOE Removed)": "Neuritic plaques density (ABC-C/CERAD Score; APOE−)",
    "CAA (APOE Removed)": "CAA Presence (APOE-)",
    # --- Vascular Cluster ---
    "Arteriolosclerosis (APOE Removed)": "Arteriolosclerosis",
    "Atherosclerosis (APOE Removed)": "Atherosclerosis",
    # --- LATE Cluster ---
    "LATE-NC (APOE Removed)": "LATE-NC (APOE-)",
    "Hippocampal Sclerosis (APOE Removed)": "Hippocampal sclerosis"
}

bar_shade = {
    "APOE": 63926,
    "AD (APOE-)": 75024,
    "Amyloid-β spread (Thal phase; APOE−)": 6363,
    "Tau Neurofibrillary tangle spread (Braak Stage; APOE−)": 7776,
    "Neuritic plaques density (ABC-C/CERAD Score; APOE−)": 7786,
    "CAA Presence (APOE-)": 7381,
    "Arteriolosclerosis": 6668,
    "Atherosclerosis": 7340,
    "LATE-NC (APOE-)": 3112,
    "Hippocampal sclerosis": 7164
}
prs_keys = {
    "Diseases": {
        #"ad_without_bigapoe_0_01": "AD (without APOE)",
        "ad_apoe": "AD",
        "pd": "PD",
        "dlb": "DLB",
        "ftd": "FTD",
        "neurodegenerative": "NDEG",
        "als": "ALS",
        "ms": "MS",
        "msa": "MSA",
        "mdd": "MDD",
        "bp": "BP",
        "scz": "SCZ"
    },
    "Traits": {
        "risk_taking": "Risk Taking",
        "intelligence": "Intelligence",
        "insomnia_schoeler_2023": "Insomnia",
        "sociability": "Sociability",
        "neuroticism_hu": "Neuroticism"
    },
    "Shade_et_al": {
        "micro": "Microinfarcts",
        "arteriol": "Arteriolosclerosis",
        "diffuse_ab": "Amyloid-β Plaques",
        "lewy": "Lewy Body",
        "braak_nft": "Braak NFT Stage",
        "late": "LATE-NC",
        "caa": "CAA",
        "atherosclerosis": "Atherosclerosis",
        "cerad": "CERAD Score",
        "grossinf": "Infarctions",
        "hs": "Hippocampal Sclerosis"
    }
}
fig_dict = {
    # --- ADNC (Alzheimer Disease Neuropathologic Change) ---
    "A": "Amyloid-β pathology spread (ABC-A)",
    "B": "Tau pathology stage (ABC-B)",
    "C": "Neuritic plaques density (ABC-C / CERAD Score)",
    "Braak_score_Tangles_(neutrofibrillary_tangles)": "Tau neurofibrillary tangles spread (Braak Stage)",
    "Braak_score_amyloid": "Amyloid-β spread (Braak Stage)",

    # --- Synuclein ---
    "Braak_score_lewy_bodies_(alphasynucleine)": "Alpha-synuclein spread (Braak Stage)",

    # --- Tauopathy (Age-related) ---
    "ARTAG_(aging_related_tau_astrogliopathy)": "Tau astrogliopathy (ARTAG)",

    # --- Amyloid Vascular Pathology ---
    "Cerebral_amyloid_angiopathy_(CAA)": "CAA presence",
    "CAA_type": "CAA type (Capillary vs Vessel)",
    "CAA_grade": "CAA severity",

    # --- Vascular Pathology ---
    "Athersclerosis": "Atherosclerosis",
    "Infarctions": "Infarctions",

    # --- Structural Changes (Macro) ---
    "Amygdala atrophy": "Amygdala atrophy",
    "Caudate nucleus abnormality": "Caudate abnormality",
    "Corpus callosum": "Corpus callosum atrophy",
    "Hippocampal_sclerosis": "Hippocampal sclerosis",
    "Hippocampal atrophy": "Hippocampus atrophy",
}

bar_disease = {
    "AD": 75024,
    "PD": 33674,
    "DLB": 2591,
    "FTD": 2154,
    "NDEG": 103388,
    "ALS": 27205,
    "MS": 14802,
    "MSA": 888,
    "MDD": 170756,
    "BP": 41917,
    "SCZ": 53386
}



# --- Target Feature Column Extraction Scope ---
feature_cols = [
    # Placeholder Baseline Columns
    'A',
    'B',
    'C',
    
    # Neurodegenerative Staging & Scores
    'Braak_score_lewy_bodies_(alphasynucleine)',
    'Braak_score_amyloid',
    'Braak_score_Tangles_(neutrofibrillary_tangles)',
    'Hippocampal_sclerosis',
    'LATE_(Limbic_pre_dominant_Age_related_TDP_43_Encephalopathy)',
    'PART (primary age related tauopathy)',
    'Agryophilic_grain_disease',
    'ARTAG_(aging_related_tau_astrogliopathy)',
    
    # Volumetric and Atrophy Measures
    'Amygdala size',
    'Hippocampal atrophy',
    'Hippocampal size',
    'Corpus callosum',
    'Amygdala atrophy',
    
    # Structural & Vascular Pathology Markers
    'Meninges / leptomeninx (transparency)',
    'Athersclerosis',
    'Infarctions',
    'Caudate nucleus abnormality',
    'Cerebral_amyloid_angiopathy_(CAA)',  
    'CAA_type',
    'CAA_grade'
]



simple_diagnosis = {

#"AD, PSYCH, SCZ":"AD",
# Psych detail
"BP, PSYCH": "BP", # "PSYCH, SCZ": "SCZ",
"MDD, PSYCH": "MDD",# "PSYCH, SCZ": "SCZ",
"PSYCH, SCZ": "Other PSYCH",
"PSYCH_other":"Other PSYCH",
"PSYCH, PTSD": "Other PSYCH",
"OCD, PSYCH": "Other PSYCH",
"NARCO, PSYCH":"Other PSYCH",
"ASD, PSYCH":"Other PSYCH",
"ADHD, PSYCH":"Other PSYCH",
# Psych detail
# "BP, PSYCH": "PSYCH", "MDD, PSYCH": "PSYCH",# "PSYCH, SCZ": "SCZ",
# "PSYCH, SCZ": "PSYCH",
# "PSYCH_other":"PSYCH",
# "PSYCH, PTSD": "PSYCH",
# "OCD, PSYCH": "PSYCH",
# "NARCO, PSYCH":"PSYCH",
# "ASD, PSYCH":"PSYCH",
# "ADHD, PSYCH":"PSYCH",

# MND together
"MND_other": "MND", "ALS, MND": "MND",

# MS together
"MS, MS-PP": "MS", "MS, MS-SP": "MS", "MS, MS-RR": "MS", "MS_undefined": "MS",
# Ataxia together
'ADCA, ATAXIA': "ATAXIA", 'ATAXIA, FA': "ATAXIA", "ATAXIA, SCA": "ATAXIA", 'ATAXIA, FXTAS': "ATAXIA",
# PD and PDD combined
"PDD": "PD",
# FTD together
"FTD, FTD-TAU, TAU": "FTD",
"FTD, PID": "FTD","FTD, FTD-TAU, PID":"FTD",
"FTD, FTD-FUS": "FTD",
"FTD_undefined": "FTD",
"FTD, FTD-TDP_undefined": "FTD",
"FTD, FTD-TDP-A, PROG": "FTD","FTD, FTD-TDP-A":"FTD",
"C9ORF72, FTD, FTD-TDP-B": "FTD","FTD, FTD-TDP-B":"FTD",
"FTD, FTD-TDP-C": "FTD",
"FTD, FTD-TDP-D":"FTD",
"FTD, FTD-UPS":"FTD",
"C9ORF72, FTD, FTD-TDP-A, FTD-TDP-B":"FTD",
"C9ORF72, FTD, FTD-TDP-B, FTD-TDP-C":"FTD",
"FTD-TDP":"FTD",
"FTD, FTD-TDP-A, FTD-TDP-D":"FTD",
"FTD, FTD-TDP-A, FTD-TDP-B, PROG":"FTD",
"FTD, FTD-TDP-B, FTD-TDP-C":"FTD",
"C9ORF72, FTD-TDP-A":"FTD",

"FTD, FTD-TDP_undefined, MND_other":"FTD-TDP + MND",
"FTD, FTD-TDP-B, MND_other":"FTD-TDP + MND",
"FTD, FTD-TDP-C, MND_other":"FTD-TDP + MND",
"FTD-TDP + MND":"FTD-TDP + MND",
"ALS, FTD, FTD-TDP-B":"FTD-TDP + MND",
"ALS, C9ORF72, FTD, FTD-TDP-B":"FTD-TDP + MND",
"ALS, C9ORF72, FTD, FTD-TDP-A, FTD-TDP-B":"FTD-TDP + MND",
"ALS, FTD, FTD-TDP-A, FTD-TDP-B":"FTD-TDP + MND",
"ALS, FTD, FTD-FUS":"FTD",
"ALS, FTD, FTD-TDP_undefined":"FTD-TDP + MND",

## dementias
'DEM, ENCEPHA, VE':'VE',#'DEM + VE',## raremixed
'AD, ENCEPHA, VE':'AD + VE',## raremixed
'ENCEPHA, VE':'VE',## raremixed
'DEM, SICC':'SICC',#'DEM + SICC',## raremixed
'DLB, SICC':'DLB + SICC',## raremixed
"AD, DLB":"AD + DLB",## raremixed
"AD, ILBD":"AD + ILBD",## raremixed
"ILBD":"ILBD",## raremixed
"AD, CA":"AD + CA",## raremixed
"AD, PD":"AD + PD",## raremixed
"AGD, DEM, SICC":"AGD",## raremixed
"AGD, FTD, FTD-TAU":"AGD",## raremixed
"CBD, FTD, FTD-TAU":"CBD",
"FTD, FTD-TAU, PSP, TAU":"PSP",



# other groups
"IS":"Vascular pathology",
"CVA":"Vascular pathology",
"CVA, DEM":"Vascular pathology",
"SEP":"Vascular pathology",

"ATPD, PD":"Other Neuropath",
"CA":"Other Neuropath",
"CJD":"Other Neuropath",
"ILBD, SICC":"Other Neuropath",
"PAL":"Other Neuropath",
"DAI":"Other Neuropath",
"NIG":"Other Neuropath",

"DEM, NAD":"Other dementia",
"KOR, WER":"Other dementia",
"DEM, ILBD, SICC":"Other dementia",
"CA, DEM, SICC":"Other dementia",
"ILBD, VD":"Other dementia",
"AD, FTD, FTD-TDP_undefined":"Other dementia",
"NHL":"Brain cancer",
"TUM":"Brain cancer",

"OTHER":"Other (excluded)",
"ENCE":"Other (excluded)",
"DOWN":"Other (excluded)",
"LD_other":"Other (excluded)",
"EPI":"Other (excluded)",
"AD, MS":"Other (excluded)",
"COHA":"Other (excluded)",
"HMSN":"Other (excluded)",
"MEDIS":"Other (excluded)",
"DEV":"Other (excluded)",
"LDA":"Other (excluded)",
"FAHR":"Other (excluded)",
"NCSD":"Other (excluded)",
"ILBD, MDD, PSYCH":"Other (excluded)",
"ENCEPHA, PML":"Other (excluded)",
"NU":"Other (excluded)",
"NMO":"Other (excluded)",
"VDCAD":"Other (excluded)",
"HSP":"Other (excluded)",
"ALEX":"Other (excluded)",
"NPA":"Other (excluded)",
"Unknown":"Other (excluded)",
"FRAGX":"Other (excluded)",
"DYSTO":"Other (excluded)",
"PCAD":"Other (excluded)",
"PWS":"Other (excluded)",
"AD, PSYCH, SCZ":"Other (excluded)"

}